name: NuGet Generation

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Buid dotnet
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup .NET Core @ Latest
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x' # SDK Version to use.
      - name: Build solution and generate NuGet package
        run: dotnet build --configuration Release --output packages
      - name: Upload NuGet package to GitHub
        uses: actions/upload-artifact@v2
        with:
          name: packages
          path: packages/ 

  release:
    runs-on: ubuntu-latest
    name: Publish NuGet package 
    needs: build
    if: github.ref == 'refs/heads/main' # only run job if on the main branch   
    steps:
      - name: Download nuget package artifact
        uses: actions/download-artifact@v1.0.0
        with:
          name: packages
      - name: Create the package
        run: dotnet pack --configuration Release --output packages
      - name: Publish the package to GPRGitHub registry
        run: dotnet nuget push "packages/*.nupkg" --source "https://nuget.pkg.github.com/kiwsan-mc/index.json" --api-key ${{ github.token }}
