name: publish
on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.x.x' # SDK Version to use.
          source-url: https://nuget.pkg.github.com/kiwsan-mc/index.json
      - run: dotnet build --configuration Release --output packages
      - name: Create the package
        run: dotnet pack --configuration Release --output packages
      - name: Publish the package to GPR
        run: dotnet nuget push "packages/*.nupkg" --api-key ${{ secrets.GH_NUGET_AUTH_TOKEN }} --no-symbols true --skip-duplicate